"""
Demo data generator for FencingMind Analytics.

Produces a realistic MatchReport dict for a foil pool bout (5-3)
that can be rendered directly by the Jinja2 report template.
"""


def generate_demo_report() -> dict:
    """Return a realistic demo MatchReport dict for a foil match (5-3)."""
    return {
        "summary": {
            "video_path": "demo_match.mp4",
            "final_score": "5-3",
            "total_touches": 8,
            "match_duration": "2:47",
            "total_frames_analyzed": 5010,
            "analysis_time_sec": 88.3,
            "weapon": "foil",
        },
        "touches": [
            {
                "touch_number": 1,
                "frame": 690,
                "video_timestamp": "0:23",
                "match_time": "0:23",
                "scorer": "left",
                "score_after": "1-0",
                "action_scorer": "attack",
                "action_confidence": 0.87,
                "action_opponent": "parry",
                "opponent_confidence": 0.72,
                "description": "왼쪽 선수의 빠른 런지 공격, 오른쪽 파리 실패",
            },
            {
                "touch_number": 2,
                "frame": 1340,
                "video_timestamp": "0:45",
                "match_time": "0:45",
                "scorer": "right",
                "score_after": "1-1",
                "action_scorer": "riposte",
                "action_confidence": 0.79,
                "action_opponent": "attack",
                "opponent_confidence": 0.83,
                "description": "왼쪽 공격 후 오른쪽 파리-리포스트 성공",
            },
            {
                "touch_number": 3,
                "frame": 1920,
                "video_timestamp": "1:04",
                "match_time": "1:04",
                "scorer": "left",
                "score_after": "2-1",
                "action_scorer": "attack",
                "action_confidence": 0.91,
                "action_opponent": "counter_attack",
                "opponent_confidence": 0.45,
                "description": "왼쪽 선수 마르쉬-아탁, 우선권 확보 후 득점",
            },
            {
                "touch_number": 4,
                "frame": 2480,
                "video_timestamp": "1:23",
                "match_time": "1:23",
                "scorer": "right",
                "score_after": "2-2",
                "action_scorer": "counter_attack",
                "action_confidence": 0.68,
                "action_opponent": "attack",
                "opponent_confidence": 0.74,
                "description": "왼쪽 준비 동작 중 오른쪽 카운터 어택 성공",
            },
            {
                "touch_number": 5,
                "frame": 3100,
                "video_timestamp": "1:43",
                "match_time": "1:43",
                "scorer": "left",
                "score_after": "3-2",
                "action_scorer": "riposte",
                "action_confidence": 0.82,
                "action_opponent": "attack",
                "opponent_confidence": 0.76,
                "description": "왼쪽 선수 파리 4번 후 리포스트 득점",
            },
            {
                "touch_number": 6,
                "frame": 3650,
                "video_timestamp": "2:02",
                "match_time": "2:02",
                "scorer": "left",
                "score_after": "4-2",
                "action_scorer": "attack",
                "action_confidence": 0.88,
                "action_opponent": "parry",
                "opponent_confidence": 0.41,
                "description": "왼쪽 선수 플레쉬 공격, 오른쪽 반응 지연",
            },
            {
                "touch_number": 7,
                "frame": 4200,
                "video_timestamp": "2:20",
                "match_time": "2:20",
                "scorer": "right",
                "score_after": "4-3",
                "action_scorer": "riposte",
                "action_confidence": 0.85,
                "action_opponent": "attack",
                "opponent_confidence": 0.80,
                "description": "왼쪽 공격 실패 후 오른쪽 정확한 리포스트",
            },
            {
                "touch_number": 8,
                "frame": 4780,
                "video_timestamp": "2:39",
                "match_time": "2:39",
                "scorer": "left",
                "score_after": "5-3",
                "action_scorer": "counter_attack",
                "action_confidence": 0.76,
                "action_opponent": "attack",
                "opponent_confidence": 0.69,
                "description": "오른쪽 마지막 공격에 왼쪽 카운터 어택으로 결승점",
            },
        ],
        "left_fencer": {
            "side": "left",
            "total_touches_scored": 5,
            "total_touches_conceded": 3,
            "action_distribution": [
                {"action": "attack", "count": 3, "percentage": 60.0},
                {"action": "riposte", "count": 1, "percentage": 20.0},
                {"action": "counter_attack", "count": 1, "percentage": 20.0},
            ],
            "most_common_action": "attack",
            "most_common_action_pct": 60.0,
        },
        "right_fencer": {
            "side": "right",
            "total_touches_scored": 3,
            "total_touches_conceded": 5,
            "action_distribution": [
                {"action": "riposte", "count": 2, "percentage": 66.7},
                {"action": "counter_attack", "count": 1, "percentage": 33.3},
            ],
            "most_common_action": "riposte",
            "most_common_action_pct": 66.7,
        },
        "insights": [
            {
                "category": "action_pattern",
                "target": "left",
                "message": "왼쪽 선수의 공격 패턴이 단조로움 - 60%가 직선 공격",
                "severity": "warning",
                "evidence": "8 터치 중 공격 3회, 리포스트 1회, 카운터 1회",
            },
            {
                "category": "defense",
                "target": "right",
                "message": "오른쪽 선수의 파리-리포스트 성공률이 높음 (66.7%)",
                "severity": "suggestion",
                "evidence": "득점 3회 중 리포스트 2회 - 방어형 전략 효과적",
            },
            {
                "category": "momentum",
                "target": "left",
                "message": "왼쪽 선수가 후반 집중력 유지 - 4-2 이후에도 결승점 획득",
                "severity": "info",
                "evidence": "터치 6~8에서 2:1 우세, 리드 상황에서 안정적 운영",
            },
            {
                "category": "technique",
                "target": "right",
                "message": "오른쪽 선수의 공격 시도 시 우선권 확보 실패 빈번",
                "severity": "warning",
                "evidence": "카운터 어택 1회 성공, 공격 주도 시 실점 다수",
            },
        ],
        "meta": {
            "phase": 2,
            "pose_model": "yolo11n-pose",
            "action_model": "videomae-kinetics400",
            "pose_enabled": True,
            "action_enabled": True,
            "confidence_threshold": 0.4,
            "source_type": "coach",
        },
    }
