"""
Demo data generator for FencingMind Analytics.

Produces realistic MatchReport dicts for:
- Pool bout: foil 5-3 (Kim Minsu vs Park Jihyun)
- DE bout: epee 15-11 (Lee Junho vs Choi Seoyeon)

These are rendered directly by the Jinja2 report template.
"""


def generate_demo_report() -> dict:
    """Return a realistic demo MatchReport dict for a foil pool bout (5-3)."""
    return {
        "summary": {
            "video_path": "demo_match.mp4",
            "final_score": "5-3",
            "total_touches": 8,
            "match_duration": "2:47",
            "total_frames_analyzed": 5010,
            "analysis_time_sec": 88.3,
            "weapon": "foil",
            "bout_type": "pool",
        },
        "touches": [
            {
                "touch_number": 1,
                "frame": 690,
                "video_timestamp": "0:23",
                "match_time": "0:23",
                "scorer": "left",
                "score_after": "1-0",
                "action_scorer": "attack",
                "action_confidence": 0.87,
                "action_opponent": "parry",
                "opponent_confidence": 0.72,
                "description": "김민수의 빠른 런지 공격, 박지현 파리 실패",
                "pose_analysis": {
                    "distance_bh": 1.35,
                    "distance_zone": "lunge",
                    "footwork_scorer": "lunge",
                    "footwork_opponent": "retreat",
                    "parry_detected": False,
                    "closing_speed_bh": 0.42,
                    "joint_angles": {
                        "hip_angle": 125.0,
                        "front_knee_angle": 108.0,
                        "trunk_lean_deg": 12.0,
                        "arm_extension_ratio": 0.88,
                    },
                },
            },
            {
                "touch_number": 2,
                "frame": 1340,
                "video_timestamp": "0:45",
                "match_time": "0:45",
                "scorer": "right",
                "score_after": "1-1",
                "action_scorer": "riposte",
                "action_confidence": 0.79,
                "action_opponent": "attack",
                "opponent_confidence": 0.83,
                "description": "김민수 공격 후 박지현 파리-리포스트 성공",
                "pose_analysis": {
                    "distance_bh": 0.95,
                    "distance_zone": "extension",
                    "footwork_scorer": "stationary",
                    "footwork_opponent": "lunge",
                    "parry_detected": True,
                    "closing_speed_bh": 0.18,
                    "joint_angles": {
                        "hip_angle": 155.0,
                        "front_knee_angle": 145.0,
                        "trunk_lean_deg": 5.0,
                        "arm_extension_ratio": 0.92,
                    },
                },
            },
            {
                "touch_number": 3,
                "frame": 1920,
                "video_timestamp": "1:04",
                "match_time": "1:04",
                "scorer": "left",
                "score_after": "2-1",
                "action_scorer": "attack",
                "action_confidence": 0.91,
                "action_opponent": "counter_attack",
                "opponent_confidence": 0.45,
                "description": "김민수 마르쉬-아탁, 우선권 확보 후 득점",
                "pose_analysis": {
                    "distance_bh": 1.62,
                    "distance_zone": "advance_lunge",
                    "footwork_scorer": "advance",
                    "footwork_opponent": "stationary",
                    "parry_detected": False,
                    "closing_speed_bh": 0.55,
                    "joint_angles": {
                        "hip_angle": 118.0,
                        "front_knee_angle": 102.0,
                        "trunk_lean_deg": 18.0,
                        "arm_extension_ratio": 0.95,
                    },
                },
            },
            {
                "touch_number": 4,
                "frame": 2480,
                "video_timestamp": "1:23",
                "match_time": "1:23",
                "scorer": "right",
                "score_after": "2-2",
                "action_scorer": "counter_attack",
                "action_confidence": 0.68,
                "action_opponent": "attack",
                "opponent_confidence": 0.74,
                "description": "김민수 준비 동작 중 박지현 카운터 어택 성공",
                "pose_analysis": {
                    "distance_bh": 1.10,
                    "distance_zone": "extension",
                    "footwork_scorer": "advance",
                    "footwork_opponent": "advance",
                    "parry_detected": False,
                    "closing_speed_bh": 0.65,
                    "joint_angles": {
                        "hip_angle": 140.0,
                        "front_knee_angle": 135.0,
                        "trunk_lean_deg": 8.0,
                        "arm_extension_ratio": 0.82,
                    },
                },
            },
            {
                "touch_number": 5,
                "frame": 3100,
                "video_timestamp": "1:43",
                "match_time": "1:43",
                "scorer": "left",
                "score_after": "3-2",
                "action_scorer": "riposte",
                "action_confidence": 0.82,
                "action_opponent": "attack",
                "opponent_confidence": 0.76,
                "description": "김민수 파리 4번 후 리포스트 득점",
                "pose_analysis": {
                    "distance_bh": 0.72,
                    "distance_zone": "infighting",
                    "footwork_scorer": "stationary",
                    "footwork_opponent": "lunge",
                    "parry_detected": True,
                    "closing_speed_bh": 0.10,
                    "joint_angles": {
                        "hip_angle": 160.0,
                        "front_knee_angle": 150.0,
                        "trunk_lean_deg": 3.0,
                        "arm_extension_ratio": 0.78,
                    },
                },
            },
            {
                "touch_number": 6,
                "frame": 3650,
                "video_timestamp": "2:02",
                "match_time": "2:02",
                "scorer": "left",
                "score_after": "4-2",
                "action_scorer": "attack",
                "action_confidence": 0.88,
                "action_opponent": "parry",
                "opponent_confidence": 0.41,
                "description": "김민수 플레쉬 공격, 박지현 반응 지연",
                "pose_analysis": {
                    "distance_bh": 1.78,
                    "distance_zone": "advance_lunge",
                    "footwork_scorer": "fleche",
                    "footwork_opponent": "retreat",
                    "parry_detected": False,
                    "closing_speed_bh": 0.82,
                    "joint_angles": {
                        "hip_angle": 110.0,
                        "front_knee_angle": 95.0,
                        "trunk_lean_deg": 25.0,
                        "arm_extension_ratio": 0.97,
                    },
                },
            },
            {
                "touch_number": 7,
                "frame": 4200,
                "video_timestamp": "2:20",
                "match_time": "2:20",
                "scorer": "right",
                "score_after": "4-3",
                "action_scorer": "riposte",
                "action_confidence": 0.85,
                "action_opponent": "attack",
                "opponent_confidence": 0.80,
                "description": "김민수 공격 실패 후 박지현 정확한 리포스트",
                "pose_analysis": {
                    "distance_bh": 0.85,
                    "distance_zone": "extension",
                    "footwork_scorer": "stationary",
                    "footwork_opponent": "lunge",
                    "parry_detected": True,
                    "closing_speed_bh": 0.15,
                    "joint_angles": {
                        "hip_angle": 150.0,
                        "front_knee_angle": 140.0,
                        "trunk_lean_deg": 6.0,
                        "arm_extension_ratio": 0.90,
                    },
                },
            },
            {
                "touch_number": 8,
                "frame": 4780,
                "video_timestamp": "2:39",
                "match_time": "2:39",
                "scorer": "left",
                "score_after": "5-3",
                "action_scorer": "counter_attack",
                "action_confidence": 0.76,
                "action_opponent": "attack",
                "opponent_confidence": 0.69,
                "description": "박지현 마지막 공격에 김민수 카운터 어택으로 결승점",
                "pose_analysis": {
                    "distance_bh": 1.05,
                    "distance_zone": "extension",
                    "footwork_scorer": "advance",
                    "footwork_opponent": "fleche",
                    "parry_detected": False,
                    "closing_speed_bh": 0.72,
                    "joint_angles": {
                        "hip_angle": 135.0,
                        "front_knee_angle": 128.0,
                        "trunk_lean_deg": 10.0,
                        "arm_extension_ratio": 0.85,
                    },
                },
            },
        ],
        "left_fencer": {
            "side": "left",
            "name": "김민수",
            "club": "최병철펜싱클럽",
            "total_touches_scored": 5,
            "total_touches_conceded": 3,
            "action_distribution": [
                {"action": "attack", "count": 3, "percentage": 60.0},
                {"action": "riposte", "count": 1, "percentage": 20.0},
                {"action": "counter_attack", "count": 1, "percentage": 20.0},
            ],
            "most_common_action": "attack",
            "most_common_action_pct": 60.0,
        },
        "right_fencer": {
            "side": "right",
            "name": "박지현",
            "club": "서울펜싱클럽",
            "total_touches_scored": 3,
            "total_touches_conceded": 5,
            "action_distribution": [
                {"action": "riposte", "count": 2, "percentage": 66.7},
                {"action": "counter_attack", "count": 1, "percentage": 33.3},
            ],
            "most_common_action": "riposte",
            "most_common_action_pct": 66.7,
        },
        "insights": [
            {
                "category": "action_pattern",
                "target": "김민수",
                "message": "김민수의 공격 편중도 60% — 리포스트/카운터 혼합으로 패턴 예측 차단 필요",
                "severity": "warning",
                "evidence": "득점 5회 중 직선 공격 3회(60%), 리포스트 1회(20%), 카운터 1회(20%)",
            },
            {
                "category": "defense",
                "target": "박지현",
                "message": "박지현의 파리-리포스트 전환율 66.7% — 수비 기반 전략이 효과적",
                "severity": "suggestion",
                "evidence": "득점 3회 중 리포스트 2회, 카운터어택 1회. 공격 주도 시도 0회",
            },
            {
                "category": "momentum",
                "target": "김민수",
                "message": "김민수 4-2 리드 후에도 결승점 획득 — 후반 집중력 우수",
                "severity": "info",
                "evidence": "터치 6~8 구간에서 2:1 우세. 리드 상황에서 플레쉬+카운터로 마무리",
            },
            {
                "category": "technique",
                "target": "박지현",
                "message": "박지현의 공격 시작 시 우선권 확보 실패율 높음 — 공격 타이밍 교정 권장",
                "severity": "warning",
                "evidence": "공격 주도 시 실점 다수. 카운터어택 1회만 성공, 나머지는 상대 우선권에 밀림",
            },
            {
                "category": "training",
                "target": "김민수",
                "message": "2-2 동점 이후 전환 시점에서 리포스트 투입 — 패턴 전환 타이밍 적절",
                "severity": "suggestion",
                "evidence": "터치 5(리포스트)로 3-2 역전 후 공격형으로 재전환. 상대 리듬 교란 효과",
            },
            {
                "category": "training",
                "target": "전체",
                "message": "양 선수 모두 후반 2분대 득점 집중 — 초반 탐색전 이후 결정력 발휘",
                "severity": "info",
                "evidence": "터치 1~4: 1:23 소요(균등), 터치 5~8: 0:56 소요(가속). 후반 밀도 2.4배",
            },
        ],
        "fencer_profile": {
            "left": {
                "distance_stats": {
                    "zone_distribution": {"lunge": 2, "extension": 2, "infighting": 1, "advance_lunge": 1},
                    "zone_success_rate": {"lunge": 1.0, "extension": 0.5, "infighting": 1.0, "advance_lunge": 0.5},
                    "preferred_zone": "lunge",
                },
                "footwork_stats": {
                    "type_distribution": {"lunge": 1, "advance": 2, "stationary": 1, "fleche": 1},
                    "preferred_footwork": "advance",
                },
                "joint_angle_stats": {
                    "avg_hip_angle": 128.0,
                    "avg_front_knee": 112.0,
                    "avg_trunk_lean": 13.6,
                    "avg_arm_extension": 0.89,
                },
                "parry_rate": 0.2,
                "weaknesses": ["advance 비율 40% — 상대에게 예측 가능한 패턴"],
                "strengths": ["lunge 거리 성공률 100% — 적정 거리 관리 우수", "infighting 성공률 100% — 근접전 강함"],
            },
            "right": {
                "distance_stats": {
                    "zone_distribution": {"extension": 2, "advance_lunge": 1},
                    "zone_success_rate": {"extension": 0.67, "advance_lunge": 0.0},
                    "preferred_zone": "extension",
                },
                "footwork_stats": {
                    "type_distribution": {"stationary": 2, "advance": 1, "lunge": 1},
                    "preferred_footwork": "stationary",
                },
                "joint_angle_stats": {
                    "avg_hip_angle": 148.0,
                    "avg_front_knee": 140.0,
                    "avg_trunk_lean": 6.3,
                    "avg_arm_extension": 0.88,
                },
                "parry_rate": 0.4,
                "weaknesses": ["공격 주도 부족 — 카운터/리포스트 의존도 높음"],
                "strengths": ["빠라드-리포스트 전환 우수 — 파리 2회 중 리포스트 2회 성공"],
            },
        },
        "meta": {
            "phase": 2,
            "pose_model": "yolo11n-pose",
            "action_model": "videomae-kinetics400",
            "pose_enabled": True,
            "action_enabled": True,
            "confidence_threshold": 0.4,
            "source_type": "coach",
        },
    }


def generate_demo_de_report() -> dict:
    """Return a realistic demo MatchReport dict for an epee DE bout (15-11)."""
    return {
        "summary": {
            "video_path": "demo_de_match.mp4",
            "final_score": "15-11",
            "total_touches": 26,
            "match_duration": "9:12",
            "total_frames_analyzed": 16560,
            "analysis_time_sec": 265.4,
            "weapon": "epee",
            "bout_type": "de",
        },
        "touches": [
            # --- Period 1 (0:00~3:00) ---
            {"touch_number": 1, "frame": 810, "video_timestamp": "0:27", "match_time": "0:27",
             "scorer": "left", "score_after": "1-0",
             "action_scorer": "attack", "action_confidence": 0.84,
             "action_opponent": "counter_attack", "opponent_confidence": 0.38,
             "description": "이준호 선제 공격, 최서연 카운터 타이밍 늦음"},
            {"touch_number": 2, "frame": 1650, "video_timestamp": "0:55", "match_time": "0:55",
             "scorer": "right", "score_after": "1-1",
             "action_scorer": "counter_attack", "action_confidence": 0.81,
             "action_opponent": "attack", "opponent_confidence": 0.77,
             "description": "이준호 전진 중 최서연 정확한 카운터어택"},
            {"touch_number": 3, "frame": 2340, "video_timestamp": "1:18", "match_time": "1:18",
             "scorer": "left", "score_after": "2-1",
             "action_scorer": "attack", "action_confidence": 0.79,
             "action_opponent": "parry", "opponent_confidence": 0.42,
             "description": "이준호 짧은 런지 공격, 최서연 거리 부족"},
            {"touch_number": 4, "frame": 2910, "video_timestamp": "1:37", "match_time": "1:37",
             "scorer": "right", "score_after": "2-2",
             "action_scorer": "remise", "action_confidence": 0.72,
             "action_opponent": "attack", "opponent_confidence": 0.65,
             "description": "최서연 르미즈로 동점 — 이준호 후퇴 부족"},
            {"touch_number": 5, "frame": 3480, "video_timestamp": "1:56", "match_time": "1:56",
             "scorer": "left", "score_after": "3-2",
             "action_scorer": "counter_attack", "action_confidence": 0.86,
             "action_opponent": "attack", "opponent_confidence": 0.73,
             "description": "최서연 공격에 이준호 카운터어택 성공"},
            {"touch_number": 6, "frame": 4200, "video_timestamp": "2:20", "match_time": "2:20",
             "scorer": "left", "score_after": "4-2",
             "action_scorer": "attack", "action_confidence": 0.90,
             "action_opponent": "parry", "opponent_confidence": 0.35,
             "description": "이준호 플레쉬 공격, 최서연 반응 지연"},
            {"touch_number": 7, "frame": 4800, "video_timestamp": "2:40", "match_time": "2:40",
             "scorer": "right", "score_after": "4-3",
             "action_scorer": "attack", "action_confidence": 0.78,
             "action_opponent": "counter_attack", "opponent_confidence": 0.50,
             "description": "최서연 발 앞 공격으로 추격"},
            {"touch_number": 8, "frame": 5280, "video_timestamp": "2:56", "match_time": "2:56",
             "scorer": "left", "score_after": "5-3",
             "action_scorer": "riposte", "action_confidence": 0.83,
             "action_opponent": "attack", "opponent_confidence": 0.79,
             "description": "이준호 파리 후 리포스트 — 1피리어드 5-3 마감"},
            # --- Period 2 (3:00~6:00) ---
            {"touch_number": 9, "frame": 5940, "video_timestamp": "3:18", "match_time": "3:18",
             "scorer": "right", "score_after": "5-4",
             "action_scorer": "attack", "action_confidence": 0.85,
             "action_opponent": "parry", "opponent_confidence": 0.44,
             "description": "최서연 2피리어드 시작과 동시에 적극 공격"},
            {"touch_number": 10, "frame": 6600, "video_timestamp": "3:40", "match_time": "3:40",
             "scorer": "right", "score_after": "5-5",
             "action_scorer": "counter_attack", "action_confidence": 0.80,
             "action_opponent": "attack", "opponent_confidence": 0.71,
             "description": "최서연 카운터어택으로 동점 — 모멘텀 전환"},
            {"touch_number": 11, "frame": 7350, "video_timestamp": "4:05", "match_time": "4:05",
             "scorer": "left", "score_after": "6-5",
             "action_scorer": "attack", "action_confidence": 0.88,
             "action_opponent": "counter_attack", "opponent_confidence": 0.47,
             "description": "이준호 마르쉬-아탁으로 리드 탈환"},
            {"touch_number": 12, "frame": 7980, "video_timestamp": "4:26", "match_time": "4:26",
             "scorer": "left", "score_after": "7-5",
             "action_scorer": "attack", "action_confidence": 0.82,
             "action_opponent": "parry", "opponent_confidence": 0.39,
             "description": "이준호 연속 공격, 최서연 방어 무너짐"},
            {"touch_number": 13, "frame": 8640, "video_timestamp": "4:48", "match_time": "4:48",
             "scorer": "right", "score_after": "7-6",
             "action_scorer": "riposte", "action_confidence": 0.84,
             "action_opponent": "attack", "opponent_confidence": 0.78,
             "description": "최서연 파리-리포스트 성공 — 격차 축소"},
            {"touch_number": 14, "frame": 9300, "video_timestamp": "5:10", "match_time": "5:10",
             "scorer": "left", "score_after": "8-6",
             "action_scorer": "counter_attack", "action_confidence": 0.76,
             "action_opponent": "attack", "opponent_confidence": 0.72,
             "description": "최서연 공격에 이준호 카운터로 안정적 리드"},
            {"touch_number": 15, "frame": 9870, "video_timestamp": "5:29", "match_time": "5:29",
             "scorer": "right", "score_after": "8-7",
             "action_scorer": "attack", "action_confidence": 0.81,
             "action_opponent": "parry", "opponent_confidence": 0.46,
             "description": "최서연 짧은 런지로 추격 지속"},
            {"touch_number": 16, "frame": 10350, "video_timestamp": "5:45", "match_time": "5:45",
             "scorer": "left", "score_after": "9-7",
             "action_scorer": "attack", "action_confidence": 0.87,
             "action_opponent": "counter_attack", "opponent_confidence": 0.43,
             "description": "이준호 전진 공격, 최서연 카운터 실패"},
            {"touch_number": 17, "frame": 10890, "video_timestamp": "6:03", "match_time": "6:03",
             "scorer": "left", "score_after": "10-7",
             "action_scorer": "riposte", "action_confidence": 0.85,
             "action_opponent": "attack", "opponent_confidence": 0.80,
             "description": "이준호 파리-리포스트 — 2피리어드 10-7 마감"},
            # --- Period 3 (6:00~9:00) ---
            {"touch_number": 18, "frame": 11520, "video_timestamp": "6:24", "match_time": "6:24",
             "scorer": "right", "score_after": "10-8",
             "action_scorer": "attack", "action_confidence": 0.83,
             "action_opponent": "parry", "opponent_confidence": 0.41,
             "description": "최서연 3피리어드 적극적 추격 시작"},
            {"touch_number": 19, "frame": 12060, "video_timestamp": "6:42", "match_time": "6:42",
             "scorer": "right", "score_after": "10-9",
             "action_scorer": "counter_attack", "action_confidence": 0.79,
             "action_opponent": "attack", "opponent_confidence": 0.74,
             "description": "최서연 연속 카운터어택으로 격차 1점까지 축소"},
            {"touch_number": 20, "frame": 12690, "video_timestamp": "7:03", "match_time": "7:03",
             "scorer": "left", "score_after": "11-9",
             "action_scorer": "attack", "action_confidence": 0.91,
             "action_opponent": "parry", "opponent_confidence": 0.38,
             "description": "이준호 결정적 플레쉬 공격 — 격차 다시 벌림"},
            {"touch_number": 21, "frame": 13290, "video_timestamp": "7:23", "match_time": "7:23",
             "scorer": "right", "score_after": "11-10",
             "action_scorer": "remise", "action_confidence": 0.74,
             "action_opponent": "attack", "opponent_confidence": 0.68,
             "description": "최서연 르미즈로 다시 1점차 — 긴장감 최고조"},
            {"touch_number": 22, "frame": 13860, "video_timestamp": "7:42", "match_time": "7:42",
             "scorer": "left", "score_after": "12-10",
             "action_scorer": "counter_attack", "action_confidence": 0.82,
             "action_opponent": "attack", "opponent_confidence": 0.75,
             "description": "최서연 공격에 이준호 침착한 카운터어택"},
            {"touch_number": 23, "frame": 14460, "video_timestamp": "8:02", "match_time": "8:02",
             "scorer": "left", "score_after": "13-10",
             "action_scorer": "attack", "action_confidence": 0.89,
             "action_opponent": "parry", "opponent_confidence": 0.37,
             "description": "이준호 연속 공격으로 3점 리드 확보"},
            {"touch_number": 24, "frame": 14970, "video_timestamp": "8:19", "match_time": "8:19",
             "scorer": "right", "score_after": "13-11",
             "action_scorer": "attack", "action_confidence": 0.80,
             "action_opponent": "counter_attack", "opponent_confidence": 0.52,
             "description": "최서연 마지막 저항, 런지로 2점 득점"},
            {"touch_number": 25, "frame": 15540, "video_timestamp": "8:38", "match_time": "8:38",
             "scorer": "left", "score_after": "14-11",
             "action_scorer": "riposte", "action_confidence": 0.86,
             "action_opponent": "attack", "opponent_confidence": 0.81,
             "description": "이준호 파리-리포스트로 매치 포인트"},
            {"touch_number": 26, "frame": 16200, "video_timestamp": "9:00", "match_time": "9:00",
             "scorer": "left", "score_after": "15-11",
             "action_scorer": "attack", "action_confidence": 0.93,
             "action_opponent": "parry", "opponent_confidence": 0.32,
             "description": "이준호 결승점 — 결정적 플레쉬로 마무리"},
        ],
        "left_fencer": {
            "side": "left",
            "name": "이준호",
            "club": "대한체육회",
            "total_touches_scored": 15,
            "total_touches_conceded": 11,
            "action_distribution": [
                {"action": "attack", "count": 8, "percentage": 53.3},
                {"action": "counter_attack", "count": 3, "percentage": 20.0},
                {"action": "riposte", "count": 3, "percentage": 20.0},
                {"action": "remise", "count": 1, "percentage": 6.7},
            ],
            "most_common_action": "attack",
            "most_common_action_pct": 53.3,
        },
        "right_fencer": {
            "side": "right",
            "name": "최서연",
            "club": "서울시청",
            "total_touches_scored": 11,
            "total_touches_conceded": 15,
            "action_distribution": [
                {"action": "attack", "count": 4, "percentage": 36.4},
                {"action": "counter_attack", "count": 3, "percentage": 27.3},
                {"action": "riposte", "count": 2, "percentage": 18.2},
                {"action": "remise", "count": 2, "percentage": 18.2},
            ],
            "most_common_action": "attack",
            "most_common_action_pct": 36.4,
        },
        "insights": [
            {
                "category": "period_analysis",
                "target": "전체",
                "message": "피리어드별 흐름: P1(5-3) 이준호 주도, P2(5-4) 균형, P3(5-4) 최서연 추격 → 이준호 마무리",
                "severity": "info",
                "evidence": "P1 이준호 +2, P2 이준호 +1, P3 이준호 +1. 최서연이 후반으로 갈수록 격차 축소",
            },
            {
                "category": "action_pattern",
                "target": "이준호",
                "message": "이준호 공격 비율 53.3% — 에페 치고는 공격적, 거리 관리와 병행 시 효과적",
                "severity": "suggestion",
                "evidence": "공격 8회, 카운터 3회, 리포스트 3회. 공격/방어 전환이 자연스러움",
            },
            {
                "category": "defense",
                "target": "최서연",
                "message": "최서연 르미즈 2회 성공 — 상대 후퇴 부족을 정확히 활용",
                "severity": "suggestion",
                "evidence": "터치 4(2-2), 터치 21(11-10) 모두 르미즈. 접근전에서 강점 발휘",
            },
            {
                "category": "momentum",
                "target": "최서연",
                "message": "최서연 3피리어드 초반 10-7에서 10-9까지 추격 — 체력 배분 우수",
                "severity": "info",
                "evidence": "P3 시작 후 연속 2득점(터치 18-19). 하지만 이준호가 11-9에서 끊어냄",
            },
            {
                "category": "training",
                "target": "이준호",
                "message": "이준호 결정적 순간(매치포인트) 정확도 93% — 승부처 집중력 탁월",
                "severity": "info",
                "evidence": "터치 25(리포스트 86%), 터치 26(공격 93%). 마지막 2터치 평균 신뢰도 89.5%",
            },
            {
                "category": "training",
                "target": "전체",
                "message": "에페 특성상 카운터어택 비율 높음 (양 선수 합계 6회/26터치 = 23%) — 거리 싸움이 핵심",
                "severity": "info",
                "evidence": "이준호 카운터 3회, 최서연 카운터 3회. 르미즈 포함 시 접근전 비율 31%",
            },
        ],
        "meta": {
            "phase": 2,
            "pose_model": "yolo11n-pose",
            "action_model": "videomae-kinetics400",
            "pose_enabled": True,
            "action_enabled": True,
            "confidence_threshold": 0.4,
            "source_type": "coach",
        },
    }
